### ISSUE TITLE
Syntax Highlighting for "Where-Object"

### ISSUE THREAD

**Issue by megan201296** [jrsconfitto/language-powershell#64] opened 2018-05-17 16:49 UTC
When I use "Where-Object" it does not highlight in turquoise like the other cmdlets. Instead "Where" highlights purple and "-Object" highlights gray. Not sure if this is purposeful but seems like it should highlight turquoise like all other cmdlets.

**Comment by jrsconfitto** [comment] 2018-05-18 17:41
Thanks for the report, i'll take a look.

**Comment by jrsconfitto** [comment] 2018-05-23 13:39
This is a duplicate of (recently revived) #53. I hope to move back to PowerShell/EditorSyntax since it's looking great right now.

**Comment by jrsconfitto** [comment] 2018-10-09 18:20
Should be taken care of by #65, thanks for your patience.

**Closed by jrsconfitto** 2018-10-09 18:20 UTC
